CREATE TABLE T_MYBATIS (
	   id NUMBER
	 , name VARCHAR2(100)
	 , today DATE
);

ALTER TABLE T_MYBATIS ADD CONSTRAINT T_MYBATIS_ID_P PRIMARY KEY(id);

CREATE SEQUENCE SEQ_MYBATIS;

INSERT INTO T_MYBATIS VALUES (SEQ_MYBATIS.NEXTVAL, 'test', SYSDATE);

SELECT * FROM T_MYBATIS;
DELETE FROM T_MYBATIS;

SELECT EMPLOYEE_ID
	 , FIRST_NAME
	 , LAST_NAME 
	 , HIRE_DATE 
	 , SALARY
  FROM EMPLOYEES
 WHERE SALARY >= 10000
   AND HIRE_DATE BETWEEN TO_DATE('1995/01/01') AND TO_DATE('2000/12/31')
   AND DEPARTMENT_ID = 80;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

  
SELECT COUNT(*) AS TOTAL 
	 , D.DEPARTMENT_NAME AS DEPT_NAME
	 , E.DEPARTMENT_ID AS DEPT_CODE
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE E.DEPARTMENT_ID = 80
-- WHERE E.DEAARTMENT_ID IN (80, 90, 100)
-- WHERE E.DEPARTMENT_ID BEWEEN 80 AND 100
 GROUP BY D.DEPARTMENT_NAME, E.DEPARTMENT_ID;
 

SELECT E.EMPLOYEE_ID
	 , E.FIRST_NAME || ' ' || E.LAST_NAME  AS EMPLOYEE_NAME
	 , E.PHONE_NUMBER
	 , E.COMMISSION_PCT
	 , E.SALARY
	 , D.DEPARTMENT_ID
	 , D.DEPARTMENT_NAME
	 , J.JOB_ID
	 , J.JOB_TITLE
	 , J.MIN_SALARY
	 , J.MAX_SALARY
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
  	ON E.DEPARTMENT_ID  = D.DEPARTMENT_ID
  JOIN JOBS J
  	ON E.JOB_ID = J.JOB_ID
 WHERE E.EMPLOYEE_ID = 100;

SELECT * FROM LOCATIONS;

SELECT COUNT(*) FROM EMPLOYEES WHERE EMPLOYEE_ID = 100;
 

SELECT * 
  FROM (SELECT ROWNUM AS NUM
	 		 , DEPARTMENT_ID
			 , DEPARTMENT_NAME
			 , MANAGER_ID
			 , LOCATION_ID
 		  FROM DEPARTMENTS)
WHERE NUM BETWEEN 11 AND 20;




DROP TABLE BOARD;

CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE board(
    boardnum NUMBER,
    boardwriter VARCHAR2(20) NOT NULL,
    boardtitle VARCHAR2(50) NOT NULL,
    boardcontent VARCHAR2(2000) NOT NULL,
    boarddate DATE DEFAULT SYSDATE,
    CONSTRAINT board_pk PRIMARY KEY(boardnum)
);

comment on TABLE  board is '게시판';
COMMENT ON COLUMN board.boardnum IS '게시판 번호';
COMMENT ON COLUMN board.boardwriter IS '게시판 작성자';
COMMENT ON COLUMN board.boardtitle IS '게시판 제목';
COMMENT ON COLUMN board.boardcontent IS '게시판 내용';
COMMENT ON COLUMN board.boarddate IS '게시판 작성일';​

SELECT * FROM BOARD;